GXX = g++
CFlages = -Wall
SDLFlages= -lSDL2

all: demo1 demo2

demo1: demo1.cpp
	$(GXX) demo1.cpp -o demo1.exe $(SDLFlages)

demo2: demo2.cpp
	$(GXX) demo2.cpp -o demo2.exe $(SDLFlages)

rmall:
	rm *.exe
